version: '3.8'

services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
        - ..:/workspace
    stdin_open: true  # apparently this is important. 🫠
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

    # mysql --host=db --user=myuser --password=mypassword mydatabase 
    # ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'example';